crypto:
    top: 100 # top N cryptos by market cap
    window: 90 # accumulative gross profit window size, unit: day
    range:

stock:
    top: 500 # top N stocks by market cap
    window: 1 # moving average window size, unit: quarter
    fmp_key:
    range:

bot_token:
